// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFah8dfsglU1GyJFyJvGt9RT8UQHlSNcE',
    appId: '1:58233352026:web:05dd1e53973e941e88cd63',
    messagingSenderId: '58233352026',
    projectId: 'my-firestore-app-9c05d',
    authDomain: 'my-firestore-app-9c05d.firebaseapp.com',
    storageBucket: 'my-firestore-app-9c05d.firebasestorage.app',
    measurementId: 'G-D0949V8948',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZil-J9c768FPwtzMEUxE5or7Ai-qqZsM',
    appId: '1:58233352026:android:9b292290b5f52c9f88cd63',
    messagingSenderId: '58233352026',
    projectId: 'my-firestore-app-9c05d',
    storageBucket: 'my-firestore-app-9c05d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvkm33-hYG8Mty_tZsgW8zm4fvR-Qt16I',
    appId: '1:58233352026:ios:dedf78dd0866de2588cd63',
    messagingSenderId: '58233352026',
    projectId: 'my-firestore-app-9c05d',
    storageBucket: 'my-firestore-app-9c05d.firebasestorage.app',
    iosBundleId: 'com.example.tugas3Ppbcs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvkm33-hYG8Mty_tZsgW8zm4fvR-Qt16I',
    appId: '1:58233352026:ios:dedf78dd0866de2588cd63',
    messagingSenderId: '58233352026',
    projectId: 'my-firestore-app-9c05d',
    storageBucket: 'my-firestore-app-9c05d.firebasestorage.app',
    iosBundleId: 'com.example.tugas3Ppbcs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFah8dfsglU1GyJFyJvGt9RT8UQHlSNcE',
    appId: '1:58233352026:web:0e32bc1cb19cd54188cd63',
    messagingSenderId: '58233352026',
    projectId: 'my-firestore-app-9c05d',
    authDomain: 'my-firestore-app-9c05d.firebaseapp.com',
    storageBucket: 'my-firestore-app-9c05d.firebasestorage.app',
    measurementId: 'G-2HGJSMP3R4',
  );
}
